/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.PopupMenu;
import javax.swing.JFrame;

/**
 *
 * @author Arthur
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); //Abrir em tela cheia
        initComponents();
        jMenuItem1.addActionListener((ActionEvent) -> {
            Pedidos p = new Pedidos();
            PainelDesktop.add(p);
            p.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        PainelDesktop = new javax.swing.JDesktopPane();
        PlanoDesktop = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuClientes = new javax.swing.JMenu();
        CadCliente = new javax.swing.JMenuItem();
        P_Cliente = new javax.swing.JMenuItem();
        ExcluirCliente = new javax.swing.JMenuItem();
        MenuFunc = new javax.swing.JMenu();
        CadFun = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        CaixaMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuPed = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ExitMenu = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        PainelDesktop.setLayer(PlanoDesktop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PainelDesktopLayout = new javax.swing.GroupLayout(PainelDesktop);
        PainelDesktop.setLayout(PainelDesktopLayout);
        PainelDesktopLayout.setHorizontalGroup(
            PainelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlanoDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelDesktopLayout.setVerticalGroup(
            PainelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlanoDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BarraMenu.setBorder(null);
        BarraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuClientes.setBackground(new java.awt.Color(0, 0, 0));
        MenuClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        MenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        MenuClientes.setText("Clientes");

        CadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        CadCliente.setText("Cadastrar");
        CadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(CadCliente);

        P_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        P_Cliente.setText("Pesquisar");
        MenuClientes.add(P_Cliente);

        ExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        ExcluirCliente.setText("Excluir");
        MenuClientes.add(ExcluirCliente);

        BarraMenu.add(MenuClientes);

        MenuFunc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        MenuFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_red.png"))); // NOI18N
        MenuFunc.setText("Funcionários");

        CadFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        CadFun.setText("Cadastrar");
        CadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFunActionPerformed(evt);
            }
        });
        MenuFunc.add(CadFun);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        jMenuItem5.setText("Pesquisar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuFunc.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMenuItem6.setText("Excluir");
        MenuFunc.add(jMenuItem6);

        BarraMenu.add(MenuFunc);

        jMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        jMenu5.setText("Fornecedor");
        BarraMenu.add(jMenu5);

        CaixaMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money_dollar.png"))); // NOI18N
        CaixaMenu.setText("Caixa");
        CaixaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaMenuActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Registrar Caixa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        CaixaMenu.add(jMenuItem2);

        BarraMenu.add(CaixaMenu);

        MenuPed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        MenuPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white.png"))); // NOI18N
        MenuPed.setText("Pedidos");
        MenuPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPedActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white_add.png"))); // NOI18N
        jMenuItem1.setText("Gerar Pedido");
        MenuPed.add(jMenuItem1);

        BarraMenu.add(MenuPed);

        jMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jMenu2.setText("Estoque");
        BarraMenu.add(jMenu2);

        ExitMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ExitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.png"))); // NOI18N
        ExitMenu.setText("Sair");
        BarraMenu.add(ExitMenu);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFunActionPerformed

        TelaCadFuncionário TelaCadFun = new TelaCadFuncionário();
        PainelDesktop.add(TelaCadFun);
        TelaCadFun.setVisible(true);
        // Cadastro de Funcionários

    }//GEN-LAST:event_CadFunActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteActionPerformed

        TelaCadClientes TelaCadClie = new TelaCadClientes();
        PainelDesktop.add(TelaCadClie);
        TelaCadClie.setVisible(true);
        // Chamar a CadClientes

    }//GEN-LAST:event_CadClienteActionPerformed

    private void CaixaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaMenuActionPerformed

        //caixa

    }//GEN-LAST:event_CaixaMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem CadCliente;
    private javax.swing.JMenuItem CadFun;
    private javax.swing.JMenu CaixaMenu;
    private javax.swing.JMenuItem ExcluirCliente;
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuFunc;
    private javax.swing.JMenu MenuPed;
    private javax.swing.JMenuItem P_Cliente;
    private javax.swing.JDesktopPane PainelDesktop;
    private javax.swing.JLabel PlanoDesktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
